#ifndef _PFDEFAULTS_H_
#define _PFDEFAULTS_H_

#define PFDEF_SEX		0
#define PFDEF_SACRIFICES	0
#define PFDEF_RELIGION  	0
#define PFDEF_CLASS		0
#define PFDEF_LEVEL           	0
#define PFDEF_THIEF_LEVEL       0 
#define PFDEF_WARRIOR_LEVEL     0 
#define PFDEF_MAGE_LEVEL        0 
#define PFDEF_CLERIC_LEVEL      0 
#define PFDEF_HOMETOWN		0
#define PFDEF_HEIGHT		0
#define PFDEF_WEIGHT		0
#define PFDEF_ALIGNMENT		0
#define PFDEF_PLRFLAGS		0
#define PFDEF_AFFFLAGS		0
#define PFDEF_SAVETHROW		0
#define PFDEF_LOADROOM		0
#define PFDEF_INVISLEV		0
#define PFDEF_FREEZELEV		0
#define PFDEF_WIMPLEV		0
#define PFDEF_CONDITION		0
#define PFDEF_BADPWS		0
#define PFDEF_PREFFLAGS		0
#define PFDEF_PREFFLAGS2	0
#define PFDEF_PRACTICES		0
#define PFDEF_GOLD		0
#define PFDEF_BANK		0
#define PFDEF_EXP		0
#define PFDEF_HITROLL		0
#define PFDEF_DAMROLL		0
#define PFDEF_AC		0
#define PFDEF_STR		0
#define PFDEF_STRADD		0
#define PFDEF_DEX		0
#define PFDEF_INT		0
#define PFDEF_WIS		0
#define PFDEF_CON		0
#define PFDEF_CHA		0
#define PFDEF_HIT		0
#define PFDEF_MAXHIT		0
#define PFDEF_MANA		0
#define PFDEF_MAXMANA		0
#define PFDEF_MOVE		0
#define PFDEF_MAXMOVE		0
#define PFDEF_HUNGER		0
#define PFDEF_THIRST		0
#define PFDEF_DRUNK		0
#define PFDEF_CLAN              0
#define PFDEF_CLANRANK          0
#define PFDEF_ROMANCE           0
#define PFDEF_PARTNER           0
#define PFDEF_HORSENAME         0
#define PFDEF_HORSEHAPPY        50
#define PFDEF_TRACKING          0
#define PFDEF_MAXHAPPY          50
#define PFDEF_HORSEROOM         255
#define PFDEF_PLRFLAGS2         0
#define PFDEF_HORSELEVEL        0
#define PFDEF_HORSEEXP          0
#define PFDEF_HORSEEQ           0
#define PFDEF_SPARRANK          1
#define PFDEF_ECONRANK          1
#define PFDEF_ASSASSINRANK      1
#define PFDEF_CAREERRANK        0
#define PFDEF_KILLS             0
#define PFDEF_DEATHS            0
#define PFDEF_TETHER_ROOM       0
#define PFDEF_GM_LEVEL          0
#define PFDEF_IS_LORD           0
#define PFDEF_LNAME             0

#endif
